/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.legnu.view;

/**
 *
 * @author Ad3ln0r
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }
    public void CadastroUsuarios(){
        cadUsuarios usuarios = new cadUsuarios();
        usuarios.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogo = new javax.swing.JLabel();
        lblEstatisticas = new javax.swing.JLabel();
        btnAgendamento = new javax.swing.JButton();
        btnPontoDeVendas = new javax.swing.JButton();
        btnOS = new javax.swing.JButton();
        btnAdministrativo = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCadastro = new javax.swing.JMenu();
        menCadastroUsuarios = new javax.swing.JMenuItem();
        menCadastroClientes = new javax.swing.JMenuItem();
        menCadastroProdutos = new javax.swing.JMenuItem();
        menCadastroOS = new javax.swing.JMenuItem();
        menCadastroPS = new javax.swing.JMenuItem();
        menRelatorios = new javax.swing.JMenu();
        menRelatoriosVendas = new javax.swing.JMenuItem();
        menRelatoriosGastos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menSobre = new javax.swing.JMenu();
        menSobreAjuda = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(31, 38, 46));
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Bem Vindo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legnu/icons/Logo_200x164.png"))); // NOI18N
        getContentPane().add(btnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, -1, -1));

        lblEstatisticas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblEstatisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legnu/icons/estatisticas.png"))); // NOI18N
        getContentPane().add(lblEstatisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, -1, 130));

        btnAgendamento.setBackground(new java.awt.Color(204, 204, 204));
        btnAgendamento.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnAgendamento.setForeground(new java.awt.Color(51, 51, 51));
        btnAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legnu/icons/iconAgendamento.png"))); // NOI18N
        btnAgendamento.setText("Agendamento");
        btnAgendamento.setActionCommand("Atalho para Ponto de Vendas ");
        btnAgendamento.setAlignmentX(0.6F);
        btnAgendamento.setAlignmentY(0.6F);
        btnAgendamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgendamento.setBorderPainted(false);
        btnAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgendamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgendamento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgendamento.setMargin(new java.awt.Insets(3, 3, 3, 3));
        getContentPane().add(btnAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 320, 60));

        btnPontoDeVendas.setBackground(new java.awt.Color(204, 204, 204));
        btnPontoDeVendas.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnPontoDeVendas.setForeground(new java.awt.Color(51, 51, 51));
        btnPontoDeVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legnu/icons/iconPdv.png"))); // NOI18N
        btnPontoDeVendas.setText("Ponto de Vendas ");
        btnPontoDeVendas.setAlignmentX(0.6F);
        btnPontoDeVendas.setAlignmentY(0.6F);
        btnPontoDeVendas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPontoDeVendas.setBorderPainted(false);
        btnPontoDeVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPontoDeVendas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPontoDeVendas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPontoDeVendas.setMargin(new java.awt.Insets(3, 3, 3, 3));
        getContentPane().add(btnPontoDeVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 320, 60));

        btnOS.setBackground(new java.awt.Color(204, 204, 204));
        btnOS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnOS.setForeground(new java.awt.Color(51, 51, 51));
        btnOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legnu/icons/iconOs.png"))); // NOI18N
        btnOS.setText("O.S");
        btnOS.setAlignmentX(0.6F);
        btnOS.setAlignmentY(0.6F);
        btnOS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOS.setBorderPainted(false);
        btnOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnOS.setMargin(new java.awt.Insets(3, 3, 3, 3));
        btnOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSActionPerformed(evt);
            }
        });
        getContentPane().add(btnOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 320, 60));

        btnAdministrativo.setBackground(new java.awt.Color(204, 204, 204));
        btnAdministrativo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnAdministrativo.setForeground(new java.awt.Color(51, 51, 51));
        btnAdministrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legnu/icons/iconAdministrativo.png"))); // NOI18N
        btnAdministrativo.setText("Administrativo");
        btnAdministrativo.setAlignmentX(0.6F);
        btnAdministrativo.setAlignmentY(0.6F);
        btnAdministrativo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministrativo.setBorderPainted(false);
        btnAdministrativo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrativo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministrativo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdministrativo.setMargin(new java.awt.Insets(3, 3, 3, 3));
        getContentPane().add(btnAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 320, 60));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legnu/icons/fundoTelaPrincipal.png"))); // NOI18N
        lblFundo.setMaximumSize(new java.awt.Dimension(1280, 700));
        lblFundo.setMinimumSize(new java.awt.Dimension(1280, 700));
        lblFundo.setPreferredSize(new java.awt.Dimension(1280, 700));
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1264, 645));

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setOpaque(false);

        menCadastro.setText("Cadastro");

        menCadastroUsuarios.setText("Usuarios");
        menCadastroUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menCadastroUsuarios.setBorderPainted(true);
        menCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroUsuariosActionPerformed(evt);
            }
        });
        menCadastro.add(menCadastroUsuarios);

        menCadastroClientes.setText("Clientes");
        menCadastroClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menCadastroClientes.setBorderPainted(true);
        menCadastro.add(menCadastroClientes);

        menCadastroProdutos.setText("Produtos");
        menCadastroProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menCadastroProdutos.setBorderPainted(true);
        menCadastro.add(menCadastroProdutos);

        menCadastroOS.setText("Ordem Servicos");
        menCadastroOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menCadastroOS.setBorderPainted(true);
        menCadastro.add(menCadastroOS);

        menCadastroPS.setText("Prestação de Serviços");
        menCadastroPS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menCadastroPS.setBorderPainted(true);
        menCadastro.add(menCadastroPS);

        jMenuBar1.add(menCadastro);

        menRelatorios.setText("Relatorios");

        menRelatoriosVendas.setText("Vendas");
        menRelatorios.add(menRelatoriosVendas);

        menRelatoriosGastos.setText("Gastos");
        menRelatorios.add(menRelatoriosGastos);

        jMenuBar1.add(menRelatorios);

        jMenu1.setText("Administrativo");

        jMenu2.setText("Cargos");
        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        menSobre.setText("Sobre");

        menSobreAjuda.setText("Ajuda");
        menSobre.add(menSobreAjuda);

        jMenuBar1.add(menSobre);

        menSair.setText("Sair");
        jMenuBar1.add(menSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1276, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOSActionPerformed

    private void menCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroUsuariosActionPerformed
     CadastroUsuarios();
    }//GEN-LAST:event_menCadastroUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrativo;
    private javax.swing.JButton btnAgendamento;
    private javax.swing.JLabel btnLogo;
    private javax.swing.JButton btnOS;
    private javax.swing.JButton btnPontoDeVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblEstatisticas;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JMenu menCadastro;
    private javax.swing.JMenuItem menCadastroClientes;
    private javax.swing.JMenuItem menCadastroOS;
    private javax.swing.JMenuItem menCadastroPS;
    private javax.swing.JMenuItem menCadastroProdutos;
    private javax.swing.JMenuItem menCadastroUsuarios;
    private javax.swing.JMenu menRelatorios;
    private javax.swing.JMenuItem menRelatoriosGastos;
    private javax.swing.JMenuItem menRelatoriosVendas;
    private javax.swing.JMenu menSair;
    private javax.swing.JMenu menSobre;
    private javax.swing.JMenuItem menSobreAjuda;
    // End of variables declaration//GEN-END:variables
}
